name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Change this to your main branch name

env: 
  REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: molten-verve-216720/avalanche-repository
  SUT_TAG: latest
  SUT_NAME: avalanche-node
  CONFIG_IMAGE: config
  CONFIG_TAG: latest


jobs:
  antithesis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: _json_key
        password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}
    
    - name: Build avalanche node
      id: build-avalanche-image
      run: |
        docker build --build-arg="RACE_FLAG=-r" -t $REGISTRY/$REPOSITORY/$SUT_NAME:$SUT_TAG -f ./Dockerfile.node.antithesis .
        echo "name=image::$REGISTRY/$REPOSITORY/$SUT_NAME:$SUT_TAG" >> $GITHUB_OUTPUT

    - name: Build config
      id: build-config-image
      run: |
        docker build --build-arg="RACE_FLAG=-r" -t $REGISTRY/$REPOSITORY/$CONFIG_NAME:$CONFIG_TAG -f ./Dockerfile.config.antithesis .
        echo "name=image::$REGISTRY/$REPOSITORY/$CONFIG_NAME:$CONFIG_TAG" >> $GITHUB_OUTPUT

    # placeholder: build workload

    - name: Publish images
      run: |
        docker push ${REGISTRY}/${REPOSITORY}/${SUT_IMAGE}:${SUT_TAG}
        docker push ${REGISTRY}/${REPOSITORY}/${CONFIG_IMAGE}:${CONFIG_TAG}

    # Run Antithesis Tests
    - name: Run Antithesis Tests
      uses: antithesishq/antithesis-trigger-action@main
      with:
        notebook_name: avalanche__smoke-baseline__latest
        tenant: avalanche
        username: ${{ secrets.ANTITHESIS_USERNAME }}
        password: ${{ secrets.ANTITHESIS_PASSWORD }}
        github_token: ${{ secrets.GH_PAT }}